### ISSUE TITLE
Find a Breakfast Recipe

### ISSUE THREAD

**Issue by maxhfine** [IntroToCode/CodeMates2_Fall22#1]
## 💬 Discussion topic

Breakfast

## ❗ Potential issues

We do not yet have a recipe for breakast!

## 👥 People to consult

@TakaHaas, please address

## 📃 Details

Please select the recipe you want to input for breakfast. It must be a sandwich!

**Comment by TakaHaas** [comment]
it must be a sandwich

**Comment by TakaHaas** [comment]
https://www.allrecipes.com/recipe/209578/blt/
