### ISSUE TITLE
Add breakfast steps

### ISSUE THREAD

**Issue by maxhfine** [IntroToCode/CodeMates2_Fall22#17]
## 💬 Discussion topic

Please add steps for breakfast

## ❗ Potential issues

I have no idea how to make a breakfast BLT

## 👥 People to consult

@TomoeWang 

## 📃 Details

Please add instructions for making breakfast BLT

**Comment by CarravitaPC** [comment]
I think @TomoeWang  is going to be handling this issue actually.  Updated accordingly.

**Comment by TomoeWang** [comment]
Yes! Added the steps :)
