### ISSUE TITLE
Dinner Missing, Assign to Tomoe

### ISSUE THREAD

**Issue by CarravitaPC** [IntroToCode/CodeMates2_Fall22#3]
## 💬 Discussion topic

No recipe or instructions listed for dinner.

## ❗ Potential issues

Sections Missing:
Recipe name
Servings
Time to prepare
Ingredients
Equipment needed
Steps for preparation

## 👥 People to consult

@TomoeWang 

## 📃 Details

Tomoe to fix the following sections:
Replace with recipe name
Servings
Time to prepare
Ingredients

**Comment by TomoeWang** [comment]
Added the 4 elements!
