### ISSUE TITLE
Help) Steps missing! Teach me how to make the dish 

### ISSUE THREAD

**Issue by TomoeWang** [IntroToCode/CodeMates2_Fall22#4]
## 💬 Discussion topic

Please add "Equipment needed" and "Steps for preparation"

## ❗ Potential issues
Starve to death. 
Missing details on "Equipment needed" and "Steps for preparation"

## 👥 People to consult

@CarravitaPC

## 📃 Details

Carravita, please add the details to the sections

**Comment by CarravitaPC** [comment]
Issue fixed, worked complete.
