### ISSUE TITLE
Dinner in wrong place!!

### ISSUE THREAD

**Issue by maxhfine** [IntroToCode/CodeMates2_Fall22#5]
## 💬 Discussion topic

Recipes

## ❗ Potential issues

Dinner recipe has been uploaded to breakfast folder!

## 👥 People to consult
@TomoeWang 

## 📃 Details

@TomoeWang please move dinner recipe out of breakfast folder to dinner folder.

**Comment by TomoeWang** [comment]
Apologies! Just moved the dinner recipe + deleted it from the breakfast folder
